### PR TITLE
[TESTMAN] Support new '[ROSAUTOTEST] ' input

### PR DESCRIPTION
**Pull request by SergeGautherie**
Match reactos PR1681.

Uncompiled; so untested.

### CODE REVIEW

**Comment by learn-more** [comment]
Uncompiled; so untested.

**Comment by ColinFinck** [comment]
I would prefer if Testman was changed to work with both old-style and new-style lines.
That should be as easy as removing the `^` character from regular expressions to match everywhere within the line (and not just at the beginning). If `substr` is used though, the statements need to be replaced with `preg_match` and corresponding regular expressions. Would also make the code easier to maintain in the long-term, as we don't need to care about string lengths anymore.

Could you do that?
Regular expressions can be comfortably tested online using https://regex101.com/

**Review by ColinFinck — CHANGES_REQUESTED** [review]
Requesting changes

**Comment by ColinFinck** [comment]
This is not worth the hassle

**Pull request closed without merging**
